### ISSUE TITLE
Double notification

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#110]
Hi,

My kresus is running full time on my cozy, and is fetching new operations every night. 
Every day (or almost) two notifications with same number of fetched operations is raised. 

I said almost, because I have doubts about the cause : 
- I  have 4 accounts, and one is my main account, so the double notification could be due to the fact that operations were fetched for two accounts (i don't think this is the case), and then, there would be a problem in the number of fetched operations in the notification
- It is a systematic situation (two notifications are always raised in this case) 

I'will check more preciselly the next days, to validate one or the oter option

**Comment by bnjbvr** [comment]
Interesting, thanks for reporting. When you say "several accounts", do you mean in several banks, or are they all in the same bank? I could imagine that having several connected banks would lead to several notifications.

**Comment by ZeHiro** [comment]
3 accounts for a bank
1 for the other (the main account)

**Comment by bnjbvr** [comment]
Should be fixed in incoming. The WeboobManager is actually a single state that was shared among all banks. Rather than rewriting the entire class to not do that, I've chosen to have one instance of WeboobManager per registered bank, which means you'll get one notification per registered bank. A more proper fix is to come, hopefully...
