### ISSUE TITLE
Import not working anymore

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#124]
Hi,

Appart from first import after install of kresus, I cannot update my accounts anymore : 
Here is the error in the log: 
when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 111, in <module>
    content = BankHistoryHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 84, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: 'module' object has no attribute 'pyopenssl'

It seems to come from the weboob,

**Comment by bnjbvr** [comment]
Thanks. Did you install Kresus on a new machine / new Docker? It seems like the pyopenssl module isn't installed while it's needed, so that might be a dependency to add to the requirements.txt file. If you get a chance, can you try adding pyopenssl to this file and reinstall weboob? (if this doesn't work, depending on which distro you are, you could try installing the package at the distro level (ubuntu: `apt install python-openssl`) but that would be unfortunate...)

**Comment by ZeHiro** [comment]
It was after the last update or so, don't remember. I try this tonight. I update the ticket  then. Thanks

**Comment by ZeHiro** [comment]
Works fine with pyopenssl in the requirements.txt

**Comment by bnjbvr** [comment]
Thanks! Mind opening a pull request into incoming for that change, please?

**Comment by ZeHiro** [comment]
Do you mind if I open one PR for operation types and this?

**Comment by bnjbvr** [comment]
No problems, as long as it's a separate commit. Actually I might take care of it this weekend, as I am planning a micro-release, so no worries.

**Comment by ZeHiro** [comment]
ok.

**Comment by bnjbvr** [comment]
(for the record, fixed on incoming)

**Comment by ZeHiro** [comment]
I saw the label ;)

**Comment by bnjbvr** [comment]
Fixed by eb5377f52803abe596b9a97770d0155a7bf2038f
