### ISSUE TITLE
Write a tutorial for installing Kresus without Cozy

### ISSUE THREAD

**Issue by hurlebouc** [bnjbvr/kresus#153]
Hello there!
Is it possible to install Kresus on a server without CozyCloud? If yes, is there a tutorial explaining how?

I would love to use this software, but without installing the whole Cozy program, since I already have my own services running independently.

**Comment by bnjbvr** [comment]
Hi! There is some work being done and which will be released in the next version so that Kresus can run independently from CozyCloud, but you can expect a less optimal experience. In particular, notifications and emails won't work at the moment. But yes, it's planned for the future, and I should make a tutorial for that. Thanks for the report.

**Comment by hurlebouc** [comment]
Great! Thank you very much!

**Comment by bnjbvr** [comment]
Hi @hurlebouc, see the tutorial at https://github.com/bnjbvr/kresus#on-debian and let me know if you think it needs modifications!

**Comment by hurlebouc** [comment]
Excellent! Thank you!

I've tried to install it on Debian, and make fails with "No rule to make
target 'install-debians-deps', needed by 'install-debian'"

**Comment by hurlebouc** [comment]
It is better, but makefile still asking for root access for installing it in /usr/local/lib/node_modules, and I don't want it to have this privileges. Moreover, it would be safer to run Kresus from it's own directory, apart from system Node modules. Is it possible to 
* build Kresus without root privileges,
* run Kresus in a isolated directory ?

**Comment by bnjbvr** [comment]
Well, you need root privileges because you've decided to install the global node packages in /usr/local/lib; although this is the default setting on npm, that can be changed. I, for one, install packages in a subdirectory of my home directory, and everything's fine :)

If you don't want to install globally, you should be able to just

- clone the repo
- cd into it
- npm install
- ln -s ./bin/kresus ~/your-local-bin/kresus (you might need to set the cwd when starting kresus...)

I'll try to see if I can add something about this in the readme.

**Comment by hurlebouc** [comment]
It works! Good job and thank you very much!

**Comment by bnjbvr** [comment]
I need to add this in the README, plus the following;

- kresus runs on port 9876, this can be changed with the env variable PORT iirc
- `make run` should really just start the standalone version, not the cozy version

**Comment by bnjbvr** [comment]
Alright, I've identified a few other issues, so I'll just close this one and open another one.
