### ISSUE TITLE
Make weboob not required anymore for dev mode

### ISSUE THREAD

**Issue by cylwin** [bnjbvr/kresus#155]
Hi,

It's always difficult to install weboob on my VM (I don't know why), it would be very nice to bypass totally weboob to try features in dev mode. Possible ?

Bye

**Comment by bnjbvr** [comment]
Hi. That's something I've wanted too, a few times, but it generates a big cross-product of versions to test (weboob-present cross cozy-present), and I also wanted to minimize that number. I figured out that not installing weboob if it were already installed would do the trick, instead. Would that work for your use case?

**Comment by ZeHiro** [comment]
HI @bnjbvr, 

when I write konnectors, I test my code by just running the app with "node build/server.js", and the vm including the full cozy in the background to provide the data-system. I do not use cozy-dev deploy. I would love to work on kresus the same way. It is currently not possible, as kresus tries to install weboob, and the install scripts are written for debian, and I work on fedora.

**Comment by bnjbvr** [comment]
@ZeHiro: how do you mean? The install script should work fine on all platforms (it's just bash and python), and if it doesn't, it's a separate bug! What happens in your case?
Myself, I now just use the standalone version for coding, it's way faster than starting the dev vm; but it's actually independent from this issue, which is about installing weboob or not :)

**Comment by ZeHiro** [comment]
@bnjbvr 

Here is how I work  for konnectors
- The cozy-dev vm runs and exposes the data-system on the appropriate port
- I develop on the host (fedora)
When I want to test, I build locally the app and run the server locally. I then test the app by directly going to localhost:konnctors_port. This does not test the right integration to cozy, but it allows to test the app globally.
It also avoids to run cozy-dev deploy <app>, as this needs to have a Vagrantfile in each app directory (which I don't want, I wans only one VM)
And no need to commit to github to test it on a cozy.

I cannot do like that with kresus as it needs to install weboob locally, and it does not seem to work (I didn't check the errors, but this could be due to non existing cozy-kresus user on the local machine, missing dependencies). I analyze this more precisely tonight and open the appropriate issue if necessary.

**Comment by cylwin** [comment]
@ZeHiro 
To use `cozy-dev deploy` you don't need au VagrantFile in each directory. You just need a VagrantFile in a parent directory.

@bnjbvr On macOSx I run also kresus in the VM in a shared folder because the weboob installation don't work. But it's not really a pain. I just have to run `cozy-monitor dev:route start kresus PORT` to test in the cozy.

**Comment by bnjbvr** [comment]
I've enhanced the feature testing so that if weboob is globally installed on the machine, Kresus won't try to download it and compile it. Would that work for you, @cylwin and @ZeHiro ?
