### ISSUE TITLE
Display the account balance in the left menu

### ISSUE THREAD

**Issue by frankrousseau** [bnjbvr/kresus#157]
Hello @bnjbvr,

When I connect to Kresus, I have to click on each account to see their balances. It would be better to see all of them in the left menu where account name are displayed. What do you think about it?

**Comment by ZeHiro** [comment]
@frankrousseau  this would mean balance computation serverside (or wait for the download of all operations of all accounts before displaying it). But it has been removed for a reason I don't know

**Comment by bnjbvr** [comment]
Good idea.

@ZeHiro : For what it's worth, I've removed the code because the balance calculation on the server was way too complicated, when a simple sum via map/reduce would be enough. All accounts and operations are already fetched at startup on the client, so it's easily doable. That being said, balance computation on the server side is needed for generating reports and alarms anyways.

**Comment by ZeHiro** [comment]
@frankrousseau What do you thinf of this?
![selection_529](https://cloud.githubusercontent.com/assets/7999082/9217637/6692f678-40ca-11e5-8539-ca6cfea5675f.png)

**Comment by frankrousseau** [comment]
It looks good! Thank you @ZeHiro!

**Comment by ZeHiro** [comment]
I added parenthesis around amount considering @bnjbvr  comments
