### ISSUE TITLE
Category sort is not "locale" sensitive

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#263]
Other text sorting could be affected.
Exemple: 
Categories:
- éléctricité
- internet

Order of display in kresus (category section, but also in drop downs) : 
- Internet
- éléctricité

Expected order : 

- électricité
- Internet

Use of https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/localeCompare
?
Pb: localeCompare not supported by Safari + Mobile browsers.

**Comment by bnjbvr** [comment]
Thanks! We should hoist all the sort functions that are used for sorting strings, and then, in the sort function, do the following:
- Use `Intl.Collator` if it's available https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator
- Otherwise, use `String.prototype.localeCompare` if it's available
- Otherwise, revert to dumb sorting (what's being done right now).

@ZeHiro or @nicofrand, any of you interested in implementing it?

**Comment by ZeHiro** [comment]
Got it!
