### ISSUE TITLE
provide logs

### ISSUE THREAD

**Issue by jeekajoo** [bnjbvr/kresus#92]
Hi,
I'm having issues with labanquepostale backend since 7/4/2015.
```
xhr error: Internal Server Error
Weboob error when importing accounts:
Error when parsing weboob json: timed out
```
I guess weboob is broken because of a change on labanquepostale side but I'd like to be sure about it.
I couldn't find any valuable logs for that.
```
/usr/local/cozy/apps/kresus# find . -name "*.log"
./node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/cozy-data-system/000005.log
./node_modules/moment/sauce_connect.log
```
Thanks

**Comment by bnjbvr** [comment]
Hi, can you try getting a look at the Kresus logs?

`cozy-monitor log kresus cat` (or `tail` instead of `cat` to follow in real time)

Also, you can update weboob from the advanced tab in settings, in the case where weboob got updated, you'll have the latest version then.

**Comment by jeekajoo** [comment]
```
Log file doesn't exist
```
in both case.

finally there is no problem with lbp, I had a problem with outgoing connections that was dropped from the container that is running cozy.

**Comment by bnjbvr** [comment]
So your issue is solved if i understand correctly ? If so, can we close the issue?

**Comment by jeekajoo** [comment]
it is solved.
but still, there is no log to troubleshoot if there is a real problem ;)

**Comment by bnjbvr** [comment]
For sure there are logs you can look at, thanks to the `cozy-monitor` commands. These log files aren't located in the `kresus` subdirectory, but that's how things work in Cozy :) If nothing is shown in the cozy-monitor logs, it's either that kresus just got restarted or that there is something fishy with the platform. Maybe we could keep a second log in the kresus directory, but I am not sure it's high value, since it would just spread information. Closing.
